import { Button } from "std-widgets.slint";

export struct NodeData {
    gain: float,
    freq: float,
    q: float,
}

export struct FreqResponse {
    freq: float,
    gain: float,
}

export component ParametricEq {

    pure callback initialize_eq_nodes(int, int, int) -> [NodeData];
    pure callback set_eq([NodeData]);
    pure callback request_eq_response([NodeData], float, float, float, float, length, length) -> image;

    width: 100%;
    height: 100%;

    out property <float> min_freq: 20;
    out property <float> max_freq: 20000;
    out property <float> min_gain: -20;
    out property <float> max_gain: 20;

    property <length> left_axis_margin: 30px;
    property <length> bottom_axis_margin: 15px;
    property <length> graph_margin: 5px;

    out property <length> draw_area_width: root.width - left_axis_margin - 2 * graph_margin;
    out property <length> graph_height: root.height * 0.8;
    out property <length> draw_area_height: graph_height - bottom_axis_margin - 2 * graph_margin;

    property <length> node_rad: 8px;

    in property <int> num_nodes: 5;
    out property <[NodeData]> eq_nodes: initialize_eq_nodes(self.num_nodes, min_freq, max_freq);

    property <bool> is_hovered;
    property <int> hovered_node;
    property <length> hovered_node_x;
    property <length> hovered_node_y;

    in-out property <image> eq_graph;
    property <bool> on_cooldown;
    property <bool> eq_changed;

    changed num_nodes => {
        self.eq_nodes = initialize_eq_nodes(self.num_nodes, min_freq, max_freq);
    }
    VerticalLayout {
        drawing_area := Rectangle {
            height: 80%;
            background: darkblue;
            Image {
                source: eq_graph;
            }
            Text {
                x: root.x + 5px;
                y: root.y + 5px;
                text: "Changed (release to set changes)";
                color: red;
                visible: root.eq_changed;
            }
            for node[i] in eq_nodes: Rectangle {
                property <bool> has_hover: is_inside(self.x + root.node_rad, self.y + root.node_rad, peq_ta.mouse-x, peq_ta.mouse-y, root.node_rad);

                x: root.node_to_x(node) - root.node_rad;
                y: root.node_to_y(node) - root.node_rad;

                width: 2 * root.node_rad;
                height: 2 * root.node_rad;

                border-radius: root.node_rad;
                border-width: 1px;
                border-color: has_hover ? blue : black;

                changed has_hover => {
                    if (self.has_hover == true && (hovered_node == i || !is_hovered)) {
                        root.hovered_node = i;
                        root.hovered_node_x = self.x + root.node_rad;
                        root.hovered_node_y = self.y + root.node_rad;
                    }
                }
            }
            peq_ta := TouchArea {
                cooldown := Timer {
                    interval: 20ms;
                    running: false;
                    triggered => {
                        root.on_cooldown = false;
                        self.running = false;
                    }
                }
                pointer-event(event) => {
                    if (event.button != PointerEventButton.left) {return;}

                    if (event.kind == PointerEventKind.down) {
                        if (is_inside(hovered_node_x, hovered_node_y, self.mouse-x, self.mouse-y, root.node_rad)) {
                            is_hovered = true;
                        }
                    }

                    if (event.kind == PointerEventKind.up) {
                        set_eq(root.eq_nodes);
                        root.eq_changed = false;
                        is_hovered = false;
                    }
                }
                moved => {
                    if (root.is_hovered) {
                        root.eq_changed = true;
                        root.eq_nodes[hovered_node].freq = Math.max(root.min_freq, Math.min(root.max_freq, x_to_freq(self.mouse-x)));
                        root.eq_nodes[hovered_node].gain = Math.max(root.min_gain, Math.min(root.max_gain, y_to_gain(self.mouse-y)));

                        hovered_node_x = self.mouse-x;
                        hovered_node_y = self.mouse-y;

                        if (!root.on_cooldown) {
                            root.eq_graph = request_eq_response(root.eq_nodes, root.min_freq, root.max_freq, root.min_gain, root.max_gain, root.width, root.height * 0.8);
                            root.on_cooldown = true;
                            cooldown.running = true;
                        }
                    }
                }
            }
        }

        Rectangle {
            background: green;
            HorizontalLayout {
                spacing: 8px;
                alignment: center;
                for node[i] in eq_nodes: Rectangle {
                    border-radius: 10px;
                    background: blue;
                    width: root.width / 5 - 8px;
                    height: 20%;
                    Text {
                        text: i + 1;
                        x: (root.x / 5) * i + 5px;
                        y: parent.y + 5px;
                    }

                    HorizontalLayout {
                        alignment: center;
                        width: 100%;
                        height: 100%;
                        VerticalLayout {
                            padding-top: 3px;
                            Text {
                                text: "Gain: " + node.gain;
                            }

                            Text {
                                text: "Freq: " + node.freq;
                            }

                            Text {
                                text: "Q: " + node.q;
                            }
                        }
                    }
                }
            }
        }
    }

    pure function is_inside(
        c_x: length, c_y: length, 
        m_x: length, m_y: length,
        r: length
    ) -> bool {
        (Math.pow((c_x - m_x) / 1px, 2) + Math.pow((c_y - m_y) / 1px, 2)) <= Math.pow(r / 1px, 2)
    }

    pure function node_to_x(
        node: NodeData,
    ) -> length {
        root.x + root.left_axis_margin + root.graph_margin + ((log(node.freq, 10)-log(root.min_freq, 10))/(log(root.max_freq, 10)-log(root.min_freq, 10))) * root.draw_area_width;
    }

    pure function x_to_freq(
        x: length,
    ) -> float {
        Math.pow(10, log(root.min_freq, 10) + ((x - root.x - root.left_axis_margin - root.graph_margin) / root.draw_area_width) * (log(root.max_freq, 10) - log(root.min_freq, 10)))
    }

    pure function node_to_y(
        node: NodeData,
    ) -> length {
        return (root.draw_area_height / 2) + graph_margin - node.gain / (root.max_gain - root.min_gain) * root.draw_area_height;
    }

    pure function y_to_gain(
        y: length,
    ) -> float {
        if (y > root.draw_area_height / 2) {
            return -((y - root.draw_area_height / 2 - root.graph_margin) / root.draw_area_height) * (root.max_gain - root.min_gain);
        } else if (y < root.draw_area_height / 2) {
            return 20 - ((y - root.graph_margin) / root.draw_area_height) * (root.max_gain - root.min_gain);
        } else {
            return 0.0;
        }
    }

}
