export component PlayerProgressBar {
    in property enabled <=> touch-area.enabled;
    in property <float> minimum: 0;
    in property <float> maximum: 100;
    in-out property <float> value: minimum;

    in property <string> left-label;
    in property <string> right-label;

    in property <color> handle-color: blue;
    in property <color> slider-color: darkgray;

    min-width: 100px;
    min-height: 12px;

    property <length> handle-x: minimum * 1px;
    property <length> handle-y: root.y;
    property <length> handle-width: 4px;
    property <length> handle-height: root.height;

    property <length> slider-size: root.width * 0.8;
    property <length> slider-offset: root.width / 10;
    
    out property <bool> handle-has-hover: touch-area.mouse-x >= root.handle-x && touch-area.mouse-x <= root.handle-x + root.handle-width &&
        touch-area.mouse-y >= root.handle-y && touch-area.mouse-y <= root.handle-y + root.handle-height;
    out property <bool> handle-pressed;

    callback handle-pressed-changed(state: bool);

    callback changed(value: float);
    callback released(value: float);

    touch-area := TouchArea {
        property <float> pressed-value;            
        
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.button != PointerEventButton.left) {
                return;
            }

            if (event.kind == PointerEventKind.up) {
                if (root.handle-pressed) {
                    root.released(root.value);
                }
                root.handle-pressed = false;
                handle-pressed-changed(false);
                return;
            }

            if (!root.handle-has-hover) {
                root.set-value(root.size-to-value(touch-area.mouse-x, slider-size));
            }

            self.pressed-value = value;
            root.handle-pressed = true;
            handle-pressed-changed(true);
        }

        moved => {
            if (!self.enabled) {
                return;
            }

            root.set-value(self.pressed-value + root.size-to-value(touch-area.mouse-x - touch-area.pressed-x + slider-offset, slider-size));
        }
    }

    HorizontalLayout {
        width: 100%;
        height: 100%;
        alignment: center;
        spacing: 3px;
        Text {
            text: left-label;
            horizontal-alignment: right;
            width: root.width * 0.10;
        }
        Rectangle {
            horizontal-stretch: 1;
            height: 6px;
            min-width: root.width * 0.8;
            y: root.height / 2 - 3px;
            background: slider-color;
            border-radius: 3px;
        }
        Text {
            text: right-label;
            horizontal-alignment: left;
            width: root.width * 0.10;
        }
    }

    handle := Rectangle {
        width: handle-width;
        height: handle-height;
        x: root.value / (root.maximum - root.minimum) * slider-size + slider-offset;

        border-radius: 2px;
        background: handle-pressed ? handle-color.darker(60%) : handle-has-hover ? handle-color.darker(20%) : handle-color.darker(40%);
    }
    


    pure function size-to-value(size: length, range: length) -> float {
        (size - slider-offset) * (root.maximum - root.minimum) / range;
    }

    function set-value(value: float) {
        if (root.value == value) {
            return;
        }

        root.changed(max(root.minimum, min(root.maximum, value)));
    }
}
